<?php

namespace Cradle\Package\IO;

use StdClass;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 13:49:45.
 */
class Cradle_Package_IO_IOPackage_Test extends TestCase
{
  /**
   * @var IOPackage
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new IOPackage;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @covers Cradle\Package\IO\IOPackage::makePayload
   */
  public function testMakePayload()
  {
    $this->object->getRequest()->setStage('foobar', 'barfoo');
    $payload = $this->object->makePayload(true);
    $this->assertEquals('barfoo', $payload['request']->getStage('foobar'));
  }
}
